export { ReactComponent as PrevIcon } from './prev.svg';
export { ReactComponent as NextIcon } from './next.svg';
export { ReactComponent as LeftIcon } from './left.svg';
export { ReactComponent as RightIcon } from './right.svg';
export { ReactComponent as SaveIcon } from './save.svg';
export { ReactComponent as VideoIcon } from './video.svg';
export { ReactComponent as PaletteIcon } from './palette.svg';
export { ReactComponent as CloseIcon } from './close.svg';
export { ReactComponent as MailIcon } from './mail.svg';